CREATE TABLE process_task (
  id BIGINT NOT NULL AUTO_INCREMENT,
  task_type VARCHAR(32) NOT NULL,
  conversation_id VARCHAR(64) NOT NULL,
  package_id BIGINT NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  priority INT NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL,
  cancel_reason VARCHAR(256) DEFAULT NULL,
  total_count INT NOT NULL DEFAULT 0,
  done_count INT NOT NULL DEFAULT 0,
  dag_json MEDIUMTEXT NOT NULL,
  payload_hash VARCHAR(128) DEFAULT NULL,
  schema_version VARCHAR(16) NOT NULL DEFAULT '1.0',
  worker_id VARCHAR(64) DEFAULT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  enqueued_at DATETIME(3) DEFAULT NULL,
  started_at DATETIME(3) DEFAULT NULL,
  finished_at DATETIME(3) DEFAULT NULL,
  heartbeat_at DATETIME(3) DEFAULT NULL,
  last_error TEXT DEFAULT NULL,
  error_msg VARCHAR(1000) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_process_task_idempotency_key (idempotency_key),
  KEY idx_process_task_status_started (status, started_at),
  KEY idx_process_task_conversation (conversation_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE process_result (
  id BIGINT NOT NULL AUTO_INCREMENT,
  task_id BIGINT NOT NULL,
  kind VARCHAR(16) NOT NULL,
  image_id VARCHAR(64) DEFAULT NULL,
  sku_id VARCHAR(64) DEFAULT NULL,
  group_key VARCHAR(64) DEFAULT NULL,
  view_id VARCHAR(64) DEFAULT NULL,
  branch_id VARCHAR(128) NOT NULL,
  source_path TEXT DEFAULT NULL,
  output_minio_key VARCHAR(512) DEFAULT NULL,
  generated_copy MEDIUMTEXT DEFAULT NULL,
  status VARCHAR(16) NOT NULL,
  error_code VARCHAR(64) DEFAULT NULL,
  error_msg VARCHAR(1000) DEFAULT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  started_at DATETIME(3) DEFAULT NULL,
  finished_at DATETIME(3) DEFAULT NULL,
  bytes_in BIGINT DEFAULT NULL,
  bytes_out BIGINT DEFAULT NULL,
  worker_run_id VARCHAR(64) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_process_result_task_image_branch (task_id, image_id, branch_id),
  KEY idx_process_result_task_group_branch (task_id, group_key, branch_id),
  KEY idx_process_result_task_status (task_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE process_result_member (
  id BIGINT NOT NULL AUTO_INCREMENT,
  result_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  image_id VARCHAR(64) NOT NULL,
  view_id VARCHAR(64) DEFAULT NULL,
  source_path TEXT DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_process_result_member_result (result_id),
  KEY idx_process_result_member_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
