ALTER TABLE asset_image
  MODIFY COLUMN original_path VARCHAR(512) NULL,
  ADD COLUMN source_type VARCHAR(16) NOT NULL DEFAULT 'ORIGINAL' AFTER display_name,
  ADD COLUMN publication_status VARCHAR(16) NOT NULL DEFAULT 'READY' AFTER source_type,
  ADD COLUMN candidate_bucket VARCHAR(32) NULL AFTER publication_status,
  ADD COLUMN candidate_key VARCHAR(512) NULL AFTER candidate_bucket,
  ADD COLUMN stable_bucket VARCHAR(32) NULL AFTER candidate_key,
  ADD COLUMN content_type VARCHAR(128) NULL AFTER stable_bucket,
  ADD COLUMN byte_size BIGINT NULL AFTER content_type,
  ADD COLUMN source_task_id BIGINT NULL AFTER byte_size,
  ADD COLUMN source_result_id BIGINT NULL AFTER source_task_id,
  ADD COLUMN source_unit_key VARCHAR(512) NULL AFTER source_result_id,
  ADD COLUMN source_run_epoch BIGINT NULL AFTER source_unit_key,
  ADD COLUMN source_image_id VARCHAR(64) NULL AFTER source_run_epoch,
  ADD COLUMN producer_kind VARCHAR(32) NULL AFTER source_image_id,
  ADD COLUMN producer_provider VARCHAR(128) NULL AFTER producer_kind,
  ADD COLUMN producer_model VARCHAR(128) NULL AFTER producer_provider,
  ADD COLUMN producer_tool VARCHAR(128) NULL AFTER producer_model,
  ADD COLUMN producer_node_id VARCHAR(128) NULL AFTER producer_tool,
  ADD COLUMN publication_error VARCHAR(1000) NULL AFTER producer_node_id,
  ADD COLUMN publication_updated_at DATETIME(3) NULL AFTER publication_error,
  ADD COLUMN ready_at DATETIME(3) NULL AFTER publication_updated_at,
  ADD COLUMN cleanup_status VARCHAR(32) NULL AFTER ready_at,
  ADD COLUMN cleanup_attempt_count INT NOT NULL DEFAULT 0 AFTER cleanup_status,
  ADD COLUMN cleanup_last_error VARCHAR(1000) NULL AFTER cleanup_attempt_count,
  ADD UNIQUE KEY uq_asset_image_source_result (source_task_id, source_result_id),
  ADD KEY idx_asset_image_publication_recovery (publication_status, publication_updated_at),
  ADD KEY idx_asset_image_cleanup_recovery (cleanup_status, publication_updated_at);

CREATE TABLE asset_image_lineage_source (
  id BIGINT NOT NULL AUTO_INCREMENT,
  asset_image_id BIGINT NOT NULL,
  ordinal INT NOT NULL,
  source_image_id VARCHAR(64) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_asset_image_lineage_ordinal (asset_image_id, ordinal),
  UNIQUE KEY uq_asset_image_lineage_source (asset_image_id, source_image_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
